spring.application.name=kursi-ge-payout-optimizer

spring.datasource.url=jdbc:postgresql://localhost:5432/payout_optimizer
spring.datasource.username=payout_user
spring.datasource.password=payout_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
